version: '4.1'

services:
    rstudio:
        image: rocker/verse:4.3.2
        platform: linux/amd64
        env_file:
            - .env
        ports:
            - 8787:8787
        volumes:
            - ./src/:/home/rstudio/src/
            - rlib:/usr/local/lib/R

volumes:
    rlib:
        external: true